# Generated by Django 3.2.7 on 2022-06-23 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('category', models.CharField(choices=[('personal', 'ব্যক্তিগত'), ('blogs', 'ব্লগ'), ('religious', 'ধর্মীয়'), ('fiction', 'ফিকশন'), ('others', 'অন্যান্য')], default='personal', max_length=100)),
                ('title', models.CharField(max_length=400)),
                ('para1', models.TextField(blank=True)),
                ('para2', models.TextField(blank=True)),
                ('para3', models.TextField(blank=True)),
                ('para4', models.TextField(blank=True)),
                ('para5', models.TextField(blank=True)),
                ('para6', models.TextField(blank=True)),
                ('para7', models.TextField(blank=True)),
                ('para8', models.TextField(blank=True)),
                ('para9', models.TextField(blank=True)),
                ('para10', models.TextField(blank=True)),
                ('para11', models.TextField(blank=True)),
                ('para12', models.TextField(blank=True)),
                ('para13', models.TextField(blank=True)),
                ('para14', models.TextField(blank=True)),
                ('para15', models.TextField(blank=True)),
                ('para16', models.TextField(blank=True)),
                ('para17', models.TextField(blank=True)),
                ('para18', models.TextField(blank=True)),
                ('para19', models.TextField(blank=True)),
                ('para20', models.TextField(blank=True)),
                ('para21', models.TextField(blank=True)),
                ('para22', models.TextField(blank=True)),
                ('para23', models.TextField(blank=True)),
                ('para24', models.TextField(blank=True)),
                ('para25', models.TextField(blank=True)),
                ('img1', models.ImageField(blank=True, upload_to='uploads')),
                ('img2', models.ImageField(blank=True, upload_to='uploads')),
                ('img3', models.ImageField(blank=True, upload_to='uploads')),
                ('img4', models.ImageField(blank=True, upload_to='uploads')),
                ('img5', models.ImageField(blank=True, upload_to='uploads')),
                ('img6', models.ImageField(blank=True, upload_to='uploads')),
                ('img7', models.ImageField(blank=True, upload_to='uploads')),
                ('img8', models.ImageField(blank=True, upload_to='uploads')),
                ('img9', models.ImageField(blank=True, upload_to='uploads')),
                ('img10', models.ImageField(blank=True, upload_to='uploads')),
            ],
        ),
    ]
