# Generated by Django 3.2.7 on 2022-06-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_number_posts_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
