# Generated by Django 3.2.7 on 2022-06-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220623_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img10caption',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='img1caption',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='img2caption',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='img3caption',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='img4caption',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='img5caption',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='img6caption',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='img7caption',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='img8caption',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='img9caption',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='img1',
            field=models.ImageField(blank=True, upload_to='static/uploads'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img10',
            field=models.ImageField(blank=True, upload_to='static/uploads'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img4',
            field=models.ImageField(blank=True, upload_to='static/uploads'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img5',
            field=models.ImageField(blank=True, upload_to='static/uploads'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img6',
            field=models.ImageField(blank=True, upload_to='static/uploads'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img7',
            field=models.ImageField(blank=True, upload_to='static/uploads'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img8',
            field=models.ImageField(blank=True, upload_to='static/uploads'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img9',
            field=models.ImageField(blank=True, upload_to='static/uploads'),
        ),
    ]
