# Generated by Django 3.2.7 on 2022-06-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220623_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('ব্যক্তিগত', 'ব্যক্তিগত'), ('ব্লগ', 'ব্লগ'), ('ধর্মীয়', 'ধর্মীয়'), ('ফিকশন', 'ফিকশন'), ('অন্যান্য', 'অন্যান্য')], default='ব্যক্তিগত', max_length=100),
        ),
    ]
