# Generated by Django 3.2.7 on 2022-06-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gratitude',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=264)),
                ('relation', models.CharField(max_length=264)),
                ('img', models.ImageField(blank=True, upload_to='static/uploads')),
                ('dedicated', models.TextField()),
            ],
        ),
    ]
