# Generated by Django 3.2.7 on 2022-06-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_gratitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='gratitude',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=100),
        ),
        migrations.AlterField(
            model_name='gratitude',
            name='img',
            field=models.ImageField(blank=True, default='static/uploads/dedicated/male.png', upload_to='static/uploads/dedicated'),
        ),
    ]
