# Generated by Django 3.2.7 on 2022-06-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220624_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gratitude',
            name='num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
